### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by iRoman1** [azu/wait-for-element.js#4]
I am getting an error in the console if the element has not been created. How can I avoid this?

**Comment by azu** [comment]
https://github.com/azu/wait-for-element.js/blob/1365ec3954f49e53d36efa4f99237019565b3372/lib/wait-by-observer.js#L34-L41

If the element has not been created until `timeout`, `waitForElement` will throw an error.
You can modify `timeout` by `waitForElement("#js-element", 2 * 1000)`.

**Comment by iRoman1** [comment]
I know, but it doesn't help. I will get the error again after this time.

**Comment by azu** [comment]
Please provide reproduce code.

- https://codesandbox.io
- https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff

**Comment by iRoman1** [comment]
```
waitForElement('.date-range-picker', 5000).then((picker_elem) => {
    const picker = new easepick.create({
            element: picker_elem,
            css: [
                '../css/daterangepicker.css',
            ],
            zIndex: 10,
            calendars: 2,
            readonly: false,
            lang: "en",
            format: "YYYY-MM-DD",
        });
}).catch(console.error.bind(console));
```
